openapi: 3.0.1
info:
  title: Self Esteem Plugin
  description: A plugin that summarizes daily sentence completions and provides 5 completions for, If any of what I wrote this week is true, it might be helpful if I.
  version: v1
servers:
  - url: http://localhost:1234
paths:
  /run:
    get:
      operationId: getPrompt
      summary: Get the prompt 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/promptResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    promptResponse:
      type: object
      properties:
        output:
          type: array
          items:
            type: string
          description: The prompt for the sentence completions.
        error:
          type: array
          items:
            type: string
          description: The error output.
    errorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message, if any.